channels:
  - uri: 'wss://mppclone.com:8443'
    _id: âœ§ğ““ğ“”ğ“¥ ğ“¡ğ“¸ğ“¸ğ“¶âœ§
    set:
      color: '#222'
      color2: '#000'
    disable:
      - getcrown
      - disabletest

user:
  name: Î»
  color: '#ff7300'
